package A.NET.ENTIDAD;
// Generated 04-jun-2015 21:38:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private String idCompra;
     private Persona persona;
     private Comprobante comprobante;
     private Usuario usuario;
     private String serie;
     private String nroC;
     private String fecha;
     private String idContacto;
     private Set compraDetalles = new HashSet(0);

    public Compra() {
    }

	
    public Compra(String idCompra) {
        this.idCompra = idCompra;
    }
    public Compra(String idCompra, Persona persona, Comprobante comprobante, Usuario usuario, String serie, String nroC, String fecha, String idContacto, Set compraDetalles) {
       this.idCompra = idCompra;
       this.persona = persona;
       this.comprobante = comprobante;
       this.usuario = usuario;
       this.serie = serie;
       this.nroC = nroC;
       this.fecha = fecha;
       this.idContacto = idContacto;
       this.compraDetalles = compraDetalles;
    }
   
    public String getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(String idCompra) {
        this.idCompra = idCompra;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Comprobante getComprobante() {
        return this.comprobante;
    }
    
    public void setComprobante(Comprobante comprobante) {
        this.comprobante = comprobante;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }
    public String getNroC() {
        return this.nroC;
    }
    
    public void setNroC(String nroC) {
        this.nroC = nroC;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public String getIdContacto() {
        return this.idContacto;
    }
    
    public void setIdContacto(String idContacto) {
        this.idContacto = idContacto;
    }
    public Set getCompraDetalles() {
        return this.compraDetalles;
    }
    
    public void setCompraDetalles(Set compraDetalles) {
        this.compraDetalles = compraDetalles;
    }




}


