package A.NET.ENTIDAD;
// Generated 04-jun-2015 21:38:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CompraDetalle generated by hbm2java
 */
public class CompraDetalle  implements java.io.Serializable {


     private CompraDetalleId id;
     private Compra compra;
     private Producto producto;
     private String cantidad;
     private String precioU;
     private String descuento;
     private Set productoDetalles = new HashSet(0);

    public CompraDetalle() {
    }

	
    public CompraDetalle(CompraDetalleId id, Compra compra, Producto producto) {
        this.id = id;
        this.compra = compra;
        this.producto = producto;
    }
    public CompraDetalle(CompraDetalleId id, Compra compra, Producto producto, String cantidad, String precioU, String descuento, Set productoDetalles) {
       this.id = id;
       this.compra = compra;
       this.producto = producto;
       this.cantidad = cantidad;
       this.precioU = precioU;
       this.descuento = descuento;
       this.productoDetalles = productoDetalles;
    }
   
    public CompraDetalleId getId() {
        return this.id;
    }
    
    public void setId(CompraDetalleId id) {
        this.id = id;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public String getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }
    public String getPrecioU() {
        return this.precioU;
    }
    
    public void setPrecioU(String precioU) {
        this.precioU = precioU;
    }
    public String getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(String descuento) {
        this.descuento = descuento;
    }
    public Set getProductoDetalles() {
        return this.productoDetalles;
    }
    
    public void setProductoDetalles(Set productoDetalles) {
        this.productoDetalles = productoDetalles;
    }




}


