package A.NET.ENTIDAD;
// Generated 04-jun-2015 21:38:01 by Hibernate Tools 4.3.1



/**
 * CompraDetalleId generated by hbm2java
 */
public class CompraDetalleId  implements java.io.Serializable {


     private String idCompra;
     private String idProducto;

    public CompraDetalleId() {
    }

    public CompraDetalleId(String idCompra, String idProducto) {
       this.idCompra = idCompra;
       this.idProducto = idProducto;
    }
   
    public String getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(String idCompra) {
        this.idCompra = idCompra;
    }
    public String getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(String idProducto) {
        this.idProducto = idProducto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CompraDetalleId) ) return false;
		 CompraDetalleId castOther = ( CompraDetalleId ) other; 
         
		 return ( (this.getIdCompra()==castOther.getIdCompra()) || ( this.getIdCompra()!=null && castOther.getIdCompra()!=null && this.getIdCompra().equals(castOther.getIdCompra()) ) )
 && ( (this.getIdProducto()==castOther.getIdProducto()) || ( this.getIdProducto()!=null && castOther.getIdProducto()!=null && this.getIdProducto().equals(castOther.getIdProducto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdCompra() == null ? 0 : this.getIdCompra().hashCode() );
         result = 37 * result + ( getIdProducto() == null ? 0 : this.getIdProducto().hashCode() );
         return result;
   }   


}


