package A.NET.ENTIDAD;
// Generated 04-jun-2015 21:38:01 by Hibernate Tools 4.3.1



/**
 * ProductoDetalleId generated by hbm2java
 */
public class ProductoDetalleId  implements java.io.Serializable {


     private String idProductoDetalle;
     private String idCompra;
     private String idProducto;

    public ProductoDetalleId() {
    }

    public ProductoDetalleId(String idProductoDetalle, String idCompra, String idProducto) {
       this.idProductoDetalle = idProductoDetalle;
       this.idCompra = idCompra;
       this.idProducto = idProducto;
    }
   
    public String getIdProductoDetalle() {
        return this.idProductoDetalle;
    }
    
    public void setIdProductoDetalle(String idProductoDetalle) {
        this.idProductoDetalle = idProductoDetalle;
    }
    public String getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(String idCompra) {
        this.idCompra = idCompra;
    }
    public String getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(String idProducto) {
        this.idProducto = idProducto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductoDetalleId) ) return false;
		 ProductoDetalleId castOther = ( ProductoDetalleId ) other; 
         
		 return ( (this.getIdProductoDetalle()==castOther.getIdProductoDetalle()) || ( this.getIdProductoDetalle()!=null && castOther.getIdProductoDetalle()!=null && this.getIdProductoDetalle().equals(castOther.getIdProductoDetalle()) ) )
 && ( (this.getIdCompra()==castOther.getIdCompra()) || ( this.getIdCompra()!=null && castOther.getIdCompra()!=null && this.getIdCompra().equals(castOther.getIdCompra()) ) )
 && ( (this.getIdProducto()==castOther.getIdProducto()) || ( this.getIdProducto()!=null && castOther.getIdProducto()!=null && this.getIdProducto().equals(castOther.getIdProducto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdProductoDetalle() == null ? 0 : this.getIdProductoDetalle().hashCode() );
         result = 37 * result + ( getIdCompra() == null ? 0 : this.getIdCompra().hashCode() );
         result = 37 * result + ( getIdProducto() == null ? 0 : this.getIdProducto().hashCode() );
         return result;
   }   


}


