package A.NET.ENTIDAD;
// Generated 04-jun-2015 21:38:01 by Hibernate Tools 4.3.1



/**
 * ProductoDetalle generated by hbm2java
 */
public class ProductoDetalle  implements java.io.Serializable {


     private ProductoDetalleId id;
     private CompraDetalle compraDetalle;
     private Byte estado;
     private String idVenta;

    public ProductoDetalle() {
    }

	
    public ProductoDetalle(ProductoDetalleId id, CompraDetalle compraDetalle) {
        this.id = id;
        this.compraDetalle = compraDetalle;
    }
    public ProductoDetalle(ProductoDetalleId id, CompraDetalle compraDetalle, Byte estado, String idVenta) {
       this.id = id;
       this.compraDetalle = compraDetalle;
       this.estado = estado;
       this.idVenta = idVenta;
    }
   
    public ProductoDetalleId getId() {
        return this.id;
    }
    
    public void setId(ProductoDetalleId id) {
        this.id = id;
    }
    public CompraDetalle getCompraDetalle() {
        return this.compraDetalle;
    }
    
    public void setCompraDetalle(CompraDetalle compraDetalle) {
        this.compraDetalle = compraDetalle;
    }
    public Byte getEstado() {
        return this.estado;
    }
    
    public void setEstado(Byte estado) {
        this.estado = estado;
    }
    public String getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(String idVenta) {
        this.idVenta = idVenta;
    }




}


