package A.NET.ENTIDAD;
// Generated 04-jun-2015 21:38:01 by Hibernate Tools 4.3.1



/**
 * VentaDetalleId generated by hbm2java
 */
public class VentaDetalleId  implements java.io.Serializable {


     private String idDetalleVenta;
     private String idVenta;

    public VentaDetalleId() {
    }

    public VentaDetalleId(String idDetalleVenta, String idVenta) {
       this.idDetalleVenta = idDetalleVenta;
       this.idVenta = idVenta;
    }
   
    public String getIdDetalleVenta() {
        return this.idDetalleVenta;
    }
    
    public void setIdDetalleVenta(String idDetalleVenta) {
        this.idDetalleVenta = idDetalleVenta;
    }
    public String getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(String idVenta) {
        this.idVenta = idVenta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VentaDetalleId) ) return false;
		 VentaDetalleId castOther = ( VentaDetalleId ) other; 
         
		 return ( (this.getIdDetalleVenta()==castOther.getIdDetalleVenta()) || ( this.getIdDetalleVenta()!=null && castOther.getIdDetalleVenta()!=null && this.getIdDetalleVenta().equals(castOther.getIdDetalleVenta()) ) )
 && ( (this.getIdVenta()==castOther.getIdVenta()) || ( this.getIdVenta()!=null && castOther.getIdVenta()!=null && this.getIdVenta().equals(castOther.getIdVenta()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdDetalleVenta() == null ? 0 : this.getIdDetalleVenta().hashCode() );
         result = 37 * result + ( getIdVenta() == null ? 0 : this.getIdVenta().hashCode() );
         return result;
   }   


}


